# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/kttech/s220/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/kttech/s220/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
	vendor/kttech/s220/proprietary/lib/libacdbmapper.so:obj/lib/libacdbmapper.so \
	vendor/kttech/s220/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

PRODUCT_COPY_FILES += \
  vendor/kttech/s220/proprietary/bin/mpdecision:system/bin/mpdecision \
  vendor/kttech/s220/proprietary/bin/netmgrd:system/bin/netmgrd \
  vendor/kttech/s220/proprietary/bin/qmuxd:system/bin/qmuxd \
  vendor/kttech/s220/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/kttech/s220/proprietary/bin/thermald:system/bin/thermald \
  vendor/kttech/s220/proprietary/bin/rild:system/bin/rild \
  vendor/kttech/s220/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
  vendor/kttech/s220/proprietary/lib/libacdbmapper.so:system/lib/libacdbmapper.so \
  vendor/kttech/s220/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
  vendor/kttech/s220/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
  vendor/kttech/s220/proprietary/lib/hw/camera.msm8660.so:system/lib/hw/camera.msm8660.so \
  vendor/kttech/s220/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/kttech/s220/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/kttech/s220/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/kttech/s220/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/kttech/s220/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/kttech/s220/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
  vendor/kttech/s220/proprietary/lib/libmmstereo.so:system/lib/libmmstereo.so \
  vendor/kttech/s220/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
  vendor/kttech/s220/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
  vendor/kttech/s220/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
  vendor/kttech/s220/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
  vendor/kttech/s220/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
  vendor/kttech/s220/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
  vendor/kttech/s220/proprietary/lib/libchromatix_mt9e013_ar.so:system/lib/libchromatix_mt9e013_ar.so \
  vendor/kttech/s220/proprietary/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
  vendor/kttech/s220/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
  vendor/kttech/s220/proprietary/lib/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
  vendor/kttech/s220/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/kttech/s220/proprietary/bin/BCM4329B1_TESTONLY.hcd:system/bin/BCM4329B1_TESTONLY.hcd \
  vendor/kttech/s220/proprietary/lib/libthermal_mitigation.so:system/lib/libthermal_mitigation.so \
  vendor/kttech/s220/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
  vendor/kttech/s220/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
  vendor/kttech/s220/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/kttech/s220/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/kttech/s220/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/kttech/s220/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/kttech/s220/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/kttech/s220/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/kttech/s220/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/kttech/s220/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/kttech/s220/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
  vendor/kttech/s220/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
  vendor/kttech/s220/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
  vendor/kttech/s220/proprietary/lib/libnv.so:system/lib/libnv.so \
  vendor/kttech/s220/proprietary/lib/libdsm.so:system/lib/libdsm.so \
  vendor/kttech/s220/proprietary/lib/libqueue.so:system/lib/libqueue.so \
  vendor/kttech/s220/proprietary/lib/libtime_remote_atom.so:system/lib/libtime_remote_atom.so \
  vendor/kttech/s220/proprietary/lib/libqdi.so:system/lib/libqdi.so \
  vendor/kttech/s220/proprietary/lib/hw/sensors.qcom.so:system/lib/hw/sensors.qcom.so \
  vendor/kttech/s220/proprietary/lib/libalps_hal.so:system/lib/libalps_hal.so \
  vendor/kttech/s220/proprietary/lib/libacdapi_azi.so:system/lib/libacdapi_azi.so \
  vendor/kttech/s220/proprietary/lib/hw/lights.msm8660.so:system/lib/hw/lights.msm8660.so \
  vendor/kttech/s220/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so
